### ISSUE TITLE
fix tpm2_import

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1079]
PR #1063 breaks tpm2_import yet again. Figure out why it broke, and fix it.

--Update -- We know why, we need to:
- [x] - fix to existing
- [x] - Support as-many-as-possible Parent algorithms
- [x] - Support name algorithm for created object (#1120)
- [x] - Support different parent name algorithms (used for hmac) (#1120)
- [x] - Support to-be-created object attributes (41b14163d2)
- [ ] - ~~Move to common public init~~ N/A - we load them from a on disk structure or PEM file.
- [x] - move OSSL to compat library to handle EVP ctx init differences, etc. (#1120)

**Comment by joshuagl** [comment]
The `import.sh` test fails with this sequence of commands:

> tpm2_createprimary -Q -G 1 -g 0xb -a o -o parent.ctx
> tpm2_evictcontrol -Q -a o -c parent.ctx -p 0x81010005
> dd if=/dev/urandom of=sym.key bs=1 count=16 2>/dev/null
> tpm2_readpublic -Q -c 0x81010005 --out-file parent.pub
> tpm2_import -Q -G aes -k sym.key -C 0x81010005 -K parent.pub -q import_key.pub -r import_key.priv

I tried manually executing this sequence of commands and replacing the tools at each step with ones built with a copy of the code before PR #1063 landed. The issue seems to be related specifically to behavioural changes in `tpm2_createprimary`:

> $ ./tools/tpm2_createprimary -Q -G 1 -g 0xb -a o -o parent.ctx
> $ ./tools/tpm2_evictcontrol -Q -a o -c parent.ctx -p 0x81010005
> $ ./tools/tpm2_readpublic -Q -c 0x81010005 --out-file parent.pub
> $ ./tools/tpm2_import -Q -G aes -k sym.key -C 0x81010005 -K parent.pub -q import_key.pub -r import_key.priv
> ERROR: Tss2_Sys_Import(0x3D5) - tpm:parameter(3):structure is the wrong size
> ERROR: Unable to run ./tools/tpm2_import

whereas with an older `tpm2_createprimary`:

> $ ~/Desktop/tpm2-tools/tools/tpm2_createprimary -Q -G 1 -g 0xb -a o -o parent.ctx
> $ ./tools/tpm2_evictcontrol -Q -a o -c parent.ctx -p 0x81010005
> $ ./tools/tpm2_readpublic -Q -c 0x81010005 --out-file parent.pub
> $ ./tools/tpm2_import -Q -G aes -k sym.key -C 0x81010005 -K parent.pub -q import_key.pub -r import_key.priv
> $ echo $?
> 0

**Comment by williamcroberts** [comment]
So for symmetric, it looks like the symmetric parameters in the primary object matter, as this works:
```
tpm2_createprimary -Q -G rsa2048:aes128cfb -g sha256 -a o -o parent.ctx
```
When `-G 1` or `-G rsa` is specified, the new algorithm defaults to "rsa2048:aes256cfb", which causes the key size not to match.

I discovered this by expanding the readpublic output and noticing the symmetric keybit size changing:
** OLD (working)**:
```
name: 000b5ab34b33bbb0d87e21018bde135f30360fe9f832560b03c98f0b1669971effee
qualified name: 000b9223473afe8c1d9b1b301ae55a12d9061edf56b8aa409ac3f8fd4788e041e57a
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
rsa-scheme: 
  value: null
  raw: 0x10
exponent: 0x0
bits: 2048
symmetric
  algorithm: 
    value: aes
    raw: 0x6
  mode:
    value: cfb
    raw: 0x43
  keybits: 128
rsa: 93a215a4000105082e40f23d59260773e43d3bc88240e52af19a7dd1c82d68ef85facecbee97d96d626da2e7d29fede080cb07d53a42fb156df43a9aba5a5c94f0e6a7d761c8e1954f39a7723ecc1e50139fc84b00a592b3a0025c59cc5117c1c585bc0e6069a5e501ae525e980f8b3c6f27a0fe91baab350c76300f5ebf0dcac296961110b47c2ff338f4a6e4bae8ec258c559f0fd9052089c2c847efbcd690a517717994e2cb46bcde6abf8e9cb63afe99d44dacd46eaa32d4f2acfe8715b696f4cd4021d03a42d487c8c27df39aaf1bbba0e23a81cc8971d2eccd539a8acac59e41dd462df0d8a1544e2614076a224c21115b3d71442ec31388d0473f9f45
```yaml
**NEW (broken)**:
```yaml
name: 000bf33efd4549ade517e026c5212a4bdf7ee67f8dae5b6705864f6b52d48fe3c75b
qualified name: 000bd3b096bbe8739a7feb6c9534c2dd7b7161ba303d844d78f75f62a8daab64ba47
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
rsa-scheme: 
  value: null
  raw: 0x10
exponent: 0x0
bits: 2048
symmetric:
  algorithm: 
    value: aes
    raw: 0x6
  mode:
    value: cfb
    raw: 0x43
  keybits: 256
rsa: b7392d940000f9dd311bf3d7152681b9645d3cc991dc210a6b3400482f06bb86050e234aafc7cd0cc2a96c630512feeeca46cf444637f3f22b3065bb4bc1c91aac404b3196bf3d75ee160fff20b17cb778f48aed135ece6ef3ff8fb1a081e7471bda6d325f971d3f221243c91a6aae4458d067ba17daf8fde11d4c48320fa67ab07c90241b52b639139a6848d3d536f4fb193980afd41a1fd4a61d9215147a495892b15e3415d6f7679a1877da0c7be60b5c0d992ff0449b1d45781e2bf50d4019230469e0f51623c75affadb28e941fa51fbecef0b803b3fe68195923007aa04503073fa12bdbf98d5eae93e1c8c03a3c383761d0790192698d2a16e269af9b
```

Not sure why this matters, or if their is a better way in creating a primary object to avoid this.... However, with this said, we can at least fix symmetric import. I'll also upstream a patch for increasing the details of the public structure to YAML for RSA.

**Comment by williamcroberts** [comment]
Ahh I am assuming this is the problem, hardcoded sym:

```
static bool import_external_key_and_save_public_private_data(TSS2_SYS_CONTEXT *sapi_context) {

    TSS2L_SYS_AUTH_COMMAND npsessionsData =
            TSS2L_SYS_AUTH_COMMAND_INIT(1, {TPMS_AUTH_COMMAND_INIT(TPM2_RS_PW)});

    TSS2L_SYS_AUTH_RESPONSE npsessionsDataOut;

    TPMT_SYM_DEF_OBJECT symmetricAlg = {
            .algorithm = TPM2_ALG_AES,
            .keyBits.aes = 128,
            .mode.aes = TPM2_ALG_CFB
    };
```

**Comment by williamcroberts** [comment]
Also looks like their is a hardcode to AES128 in the encryption routine....(sic)

**Comment by williamcroberts** [comment]
According to section [22.4](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf), I quote, "The block cipher used for encrypting the object's sensitive area is the symmetric cipher of the Storage Parent."

So the storage parent determines the cipher. I tried switching this to be generic, but when using a parent of 256, I got the same error.

**Comment by williamcroberts** [comment]
Hypothesis: Looks like the calls to KDFa have (TPM2_MAX_SYM_BLOCK_SIZE * 8) which is limiting the key to 128 bits.

This tool is more of a mess then I initially thought. Looks like parent name alg, and a host of other things were taken for granted.

**Comment by williamcroberts** [comment]
I have it working now for an RSA2048 parent that has either an AES128CFB or AES256CFB parent:
https://github.com/williamcroberts/tpm2.0-tools/tree/fix-import

Now that I got a better handle on the problem, and that it alligns to 22.4 of https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf I can go through and start to re-organize it, and remove some of these limitations.
